version: '3.5'
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:pgpwd4habr@pg:5432/postgres
      CONFIG_NAME: DevConfig
    volumes:
    - ./blog:/app/blog
    ports:
    - "5000:5000"
    depends_on:
    - pg
  pg:
    image: postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpwd4habr
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ${HOME}/dbs/flask-lesson/pgdata_dev:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"