"""add relation articles field to author model

Revision ID: 499e59db6bb5
Revises: f4f95849cb47
Create Date: 2023-04-12 00:19:45.042787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499e59db6bb5'
down_revision = 'f4f95849cb47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
