"""add unq email field to user model

Revision ID: 585cb5fc70e5
Revises: 7af152e4b307
Create Date: 2023-04-11 23:30:59.481126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585cb5fc70e5'
down_revision = '7af152e4b307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
